package com.kdevlab.basemod;

import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin;

import java.util.Map;

/**
 * Created by kirill (KDevLab) on 03.04.17.
 */
@IFMLLoadingPlugin.TransformerExclusions ({ "com.kdevlab." })
@IFMLLoadingPlugin.Name ("KDevLab Loading Plugin")
public class LoadingPlugin implements IFMLLoadingPlugin {

    public static final String MODID = "basemod";
    public static final String NAME = "BaseMod";
    public static final String VERSION = "@VERSION@";

    public static boolean isObfuscated = false;

    @Override
    public String[] getASMTransformerClass() {
        return new String[] { "com.kdevlab.basemod.asm.ClassTransformer" };
    }

    @Override
    public String getModContainerClass() {
        return KDevLabDummyContainer.class.getName();
    }

    @Override
    public String getSetupClass() {
        return null;
    }

    @Override
    public void injectData(Map<String, Object> data) {
        isObfuscated = (Boolean) data.get("runtimeDeobfuscationEnabled");
    }

    @Override
    public String getAccessTransformerClass() {
        return null;
    }

    public static class KDevLabDummyContainer extends DummyModContainer {

        private final ModMetadata meta = new ModMetadata();

        public KDevLabDummyContainer() {
            this.meta.autogenerated = false;
            this.meta.authorList.add("KDevLab");
            this.meta.credits = "Created by KDevLab.";
            this.meta.modId = this.getModId();
            this.meta.name = this.getName();
            this.meta.version = this.getVersion();
            this.meta.url = "https://github.com/miuirussia/BaseMod";
        }

        @Override
        public boolean registerBus(EventBus bus, LoadController controller)
        {
            return true;
        }

        @Override
        public String getModId()
        {
            return MODID;
        }

        @Override
        public String getName()
        {
            return NAME;
        }

        @Override
        public String getVersion()
        {
            return VERSION;
        }

        @Override
        public String getDisplayVersion()
        {
            return this.getVersion();
        }

        @Override
        public ModMetadata getMetadata()
        {
            return this.meta;
        }
    }

}
